name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build binary
        run: npm run build
      
      - name: Make binary executable
        run: chmod +x dist/file-organizer
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: file-organizer-binary
          path: dist/file-organizer

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: file-organizer-binary
          path: dist/
      
      - name: Make binary executable
        run: chmod +x dist/file-organizer
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/file-organizer
          body: |
            ## 🚀 Installation
            
            ### Quick Install (Ubuntu/Linux)
            ```bash
            wget -O file-organizer https://github.com/${{ github.repository }}/releases/latest/download/file-organizer && chmod +x file-organizer && sudo mv file-organizer /usr/local/bin/
            ```
            
            ### Manual Download
            1. Download the `file-organizer` binary below
            2. Make it executable: `chmod +x file-organizer`
            3. Move to PATH: `sudo mv file-organizer /usr/local/bin/`
            
            ### Usage
            ```bash
            file-organizer --help
            file-organizer interactive
            file-organizer organize /path/to/directory --dry-run
            ```
            
            ## 📋 What's Changed
            - Bug fixes and improvements
            - Enhanced file organization capabilities
            
            **Full Changelog**: https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}